import {chromium} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const origin=process.env.OYR_TEST_ORIGIN||'http://localhost:5173';
const browser=await chromium.launch({headless:true,executablePath:process.env.OYR_BROWSER_EXECUTABLE||undefined});
const reports=[];await mkdir('work/qa',{recursive:true});
const pdf=Buffer.from('%PDF-1.4\n1 0 obj<</Type/Catalog>>endobj\n%%EOF');
for(const [name,viewport] of [['desktop',{width:1440,height:1000}],['mobile',{width:390,height:844}]]){const context=await browser.newContext({viewport});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);await page.getByRole('link',{name:'Start Registration',exact:false}).first().click();await page.getByLabel('New Polish flag registration',{exact:true}).check();await page.getByLabel('Vessel length (metres)',{exact:true}).fill('11');await page.locator('select[name="intendedUse"]').selectOption('PRIVATE');await page.locator('select[name="mmsi"]').selectOption('POLISH_MMSI');await page.locator('select[name="priority"]').selectOption('STANDARD');await page.locator('select[name="delivery"]').selectOption('REGISTERED_MAIL');await page.getByRole('button',{name:'Save & continue'}).click();await page.getByLabel('Full/legal name',{exact:true}).fill('Ocean '+name+' Test');await page.getByLabel('Email',{exact:true}).fill(name+'@example.test');await page.getByLabel('Phone',{exact:true}).fill('+44123456789');await page.getByLabel('Address',{exact:true}).fill('1 Test Marina');await page.getByLabel('City',{exact:true}).fill('Test Harbour');await page.getByLabel('Country',{exact:true}).fill('United Kingdom');await page.getByRole('button',{name:'Save & continue'}).click();await page.getByLabel('Vessel name',{exact:true}).fill('Horizon '+name);await page.locator('select[name="type"]').selectOption('Motor yacht');await page.getByRole('button',{name:'Save & continue'}).click();await page.getByLabel('Choose document',{exact:true}).setInputFiles({name:'ownership.pdf',mimeType:'application/pdf',buffer:pdf});await page.getByRole('button',{name:'Upload document'}).click();await page.getByText('ownership.pdf',{exact:true}).waitFor();await page.getByRole('button',{name:'Review application'}).click();await page.getByRole('heading',{name:'Review & submit'}).waitFor();await page.screenshot({path:`work/qa/${name}-review.png`,fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Customer page should not overflow');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Submit application'}).click();await page.getByRole('heading',{name:'Application submitted'}).waitFor();const reference=(await page.locator('#reference').textContent()).trim();assert.match(reference,/^OYR-[A-Z2-9]{12}$/);await page.screenshot({path:`work/qa/${name}-submitted.png`,fullPage:true});
const admin=await context.newPage();await admin.goto(origin+'/admin');await admin.getByRole('link',{name:'Sign in with ChatGPT'}).click();await admin.getByRole('heading',{name:'Applications, considered.'}).waitFor();await admin.getByRole('link',{name:reference,exact:true}).click();await admin.getByRole('heading',{name:'Applicant',exact:true}).waitFor();await admin.getByText('Ocean '+name+' Test',{exact:true}).waitFor();await admin.getByText('ownership.pdf',{exact:true}).waitFor();const [download]=await Promise.all([admin.waitForEvent('download'),admin.getByRole('link',{name:'Download',exact:true}).click()]);assert.equal(download.suggestedFilename(),'ownership.pdf');await admin.locator('select[name="status"]').selectOption('UNDER_REVIEW');await admin.getByLabel('Customer-visible update',{exact:true}).fill('Your documents are being reviewed by Ocean.');await admin.getByRole('button',{name:'Update status'}).click();await admin.getByText('Your documents are being reviewed by Ocean.',{exact:true}).waitFor();await admin.screenshot({path:`work/qa/${name}-admin-review.png`,fullPage:true});
await page.goto(origin+'/track');await page.getByLabel('OYR reference',{exact:true}).fill(reference);await page.getByLabel('Application email',{exact:true}).fill(name+'@example.test');await page.getByRole('button',{name:'Track registration'}).click();await page.getByText('Your documents are being reviewed by Ocean.',{exact:true}).waitFor();assert.equal(await page.locator('#tracking-result .status').textContent(),'Under review');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Tracking should not overflow');await page.screenshot({path:`work/qa/${name}-tracking.png`,fullPage:true});assert.deepEqual(errors,[]);reports.push({viewport:name,reference,status:'UNDER_REVIEW',steps:'all 19 passed',consoleErrors:errors});await context.close();}
await browser.close();await writeFile('work/qa/browser-results.json',JSON.stringify(reports,null,2));console.log(JSON.stringify(reports,null,2));
