import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {getPlatformProxy} from 'wrangler';
import {readFile,readdir,mkdir,rm} from 'node:fs/promises';
import worker from '../dist/server/index.js';
let platform,env,app,reference,version,docId;
const origin='https://ocean.test';
const pdf=new TextEncoder().encode('%PDF-1.4\n1 0 obj<</Type/Catalog>>endobj\n%%EOF');
const adminHeaders={'oai-authenticated-user-id':'test-admin','oai-authenticated-user-email':'abdulshahin60@gmail.com'};
async function call(path,{method='GET',body,cookie='',headers={}}={}){const h={origin,'x-oyr-request':'1',...headers};if(cookie)h.cookie=cookie;if(body&&!(body instanceof FormData))h['content-type']='application/json';const req=new Request(origin+path,{method,headers:h,body:body instanceof FormData?body:body?JSON.stringify(body):undefined});const res=await worker.fetch(req,env,{});const data=res.headers.get('content-type')?.includes('application/json')?await res.json():await res.text();return {status:res.status,data,headers:res.headers};}
async function draft(){const r=await call('/api/draft',{method:'POST'});assert.equal(r.status,201);return {cookie:r.headers.get('set-cookie').split(';')[0],data:r.data};}
async function fill(session){let r;const values={package:{serviceId:'new-registration',length:11,intendedUse:'PRIVATE',mmsi:'POLISH_MMSI',priority:'STANDARD',delivery:'REGISTERED_MAIL',price:1,status:'COMPLETED'},applicant:{name:'Workflow Test',email:'workflow@example.test',phone:'+44123456789',address:'1 Test Harbour',city:'Port Test',postalCode:'T1',country:'United Kingdom',role:'ADMIN'},yacht:{name:'Test Horizon',type:'Motor yacht',builder:'Test Builder',model:'18',buildYear:2022,identification:'TEST-18',currentFlag:'Test flag'}};for(const [step,data] of Object.entries(values)){r=await call('/api/draft',{method:'PATCH',cookie:session.cookie,body:{step,data,version:session.data.version}});assert.equal(r.status,200);session.data=r.data;}const file=new FormData();file.set('type','Proof of ownership');file.set('file',new File([pdf],'ownership.pdf',{type:'application/pdf'}));r=await call('/api/draft/documents',{method:'POST',cookie:session.cookie,body:file});assert.equal(r.status,201);session.data=r.data;return session;}
before(async()=>{await mkdir('work',{recursive:true});platform=await getPlatformProxy({configPath:'wrangler.jsonc',persist:{path:'work/integration-db-'+Date.now()}});env=platform.env;const files=(await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort();for(const file of files){const sql=await readFile('drizzle/'+file,'utf8');for(const part of sql.split('--> statement-breakpoint').map(x=>x.trim()).filter(Boolean))await env.DB.prepare(part).run();}});
after(async()=>{await platform?.dispose();});
test('Complete persisted workflow, privacy and authorization',async()=>{
assert.equal((await call('/api/admin/applications')).status,401);
assert.equal((await call('/api/admin/applications',{headers:{...adminHeaders,'oai-authenticated-user-email':'stranger@example.test'}})).status,403);
assert.equal((await call('/api/draft',{method:'POST',headers:{origin:'https://evil.test'}})).status,403);
app=await fill(await draft());docId=app.data.documents[0].id;
const other=await draft();assert.equal((await call('/api/draft/documents/'+docId,{method:'DELETE',cookie:other.cookie})).status,404);
assert.equal((await call('/api/admin/documents/'+docId)).status,401);
assert.equal((await call('/api/draft/submit',{method:'POST',cookie:app.cookie,body:{version:app.data.version,consent:false,consentVersion:'oyr-registration-v1'}})).status,400);
const invalidFile=new FormData();invalidFile.set('type','Other supporting document');invalidFile.set('file',new File(['<script>alert(1)</script>'],'fake.pdf',{type:'application/pdf'}));assert.equal((await call('/api/draft/documents',{method:'POST',cookie:app.cookie,body:invalidFile})).status,400);
const r=await call('/api/draft/submit',{method:'POST',cookie:app.cookie,body:{version:app.data.version,consent:true,consentVersion:'oyr-registration-v1',price:1,status:'COMPLETED',customerId:'attacker'}});assert.equal(r.status,201);assert.match(r.data.reference,/^OYR-[A-Z2-9]{12}$/);assert.equal(r.data.status,'SUBMITTED');assert.equal(r.data.pricing.mode,'FIXED');assert.equal(r.data.pricing.amountMinor,61400);assert.equal(r.data.pricing.currency,'EUR');reference=r.data.reference;
const again=await call('/api/draft/submit',{method:'POST',cookie:app.cookie,body:{}});assert.equal(again.data.reference,reference);
const row=await env.DB.prepare('SELECT * FROM applications WHERE reference=?').bind(reference).first();assert.equal(row.status,'SUBMITTED');assert.ok(row.customer_id);assert.ok(row.vessel_id);assert.ok(row.submitted_at);assert.ok(row.consent_at);assert.notEqual(row.id,reference);
assert.equal((await env.DB.prepare('SELECT count(*) AS n FROM application_status_history WHERE application_id=?').bind(row.id).first()).n,1);
assert.equal((await env.DB.prepare('SELECT count(*) AS n FROM notifications WHERE application_id=?').bind(row.id).first()).n,1);
const list=await call('/api/admin/applications',{headers:adminHeaders});assert.equal(list.status,200);assert.equal(list.data.items[0].reference,reference);
let detail=await call('/api/admin/applications/'+reference,{headers:adminHeaders});assert.equal(detail.data.customer.name,'Workflow Test');assert.equal(detail.data.vessel.name,'Test Horizon');assert.equal(detail.data.documents.length,1);version=detail.data.version;
const download=await call('/api/admin/documents/'+docId,{headers:adminHeaders});assert.equal(download.status,200);assert.match(download.headers.get('content-disposition'),/^attachment/);assert.match(download.data,/%PDF/);
assert.equal((await call('/api/admin/applications/'+reference+'/status',{method:'POST',headers:adminHeaders,body:{status:'COMPLETED',version}})).status,409);
assert.equal((await call('/api/admin/applications/'+reference+'/status',{method:'POST',headers:adminHeaders,body:{status:'UNDER_REVIEW',version,message:'Your documents are being reviewed.'}})).status,200);
assert.equal((await call('/api/admin/applications/'+reference+'/status',{method:'POST',headers:adminHeaders,body:{status:'PROCESSING',version,message:'stale'}})).status,409);
const track=await call('/api/track',{method:'POST',body:{reference,email:'workflow@example.test'}});assert.equal(track.data.application.status,'UNDER_REVIEW');assert.equal(track.data.application.history.length,2);assert.equal(track.data.application.history[1].message,'Your documents are being reviewed.');for(const forbidden of ['customer_id','vessel_id','storage_key','changedBy','actor','email','phone','address','identity'])assert.ok(!JSON.stringify(track.data).includes(forbidden),forbidden);
const bad=await call('/api/track',{method:'POST',body:{reference,email:'wrong@example.test'}});const missing=await call('/api/track',{method:'POST',body:{reference:'OYR-NOTFOUND1234',email:'wrong@example.test'}});assert.deepEqual(bad.data,missing.data);
await assert.rejects(()=>env.DB.prepare("UPDATE application_status_history SET to_status='COMPLETED' WHERE application_id=?").bind(row.id).run());
await assert.rejects(()=>env.DB.prepare('DELETE FROM application_status_history WHERE application_id=?').bind(row.id).run());
assert.equal((await call('/api/draft',{method:'PATCH',cookie:app.cookie,body:{step:'package',data:{},version}})).status,409);
});
test('Server validates data, draft versions and upload limits',async()=>{const s=await draft();assert.equal((await call('/api/draft/submit',{method:'POST',cookie:s.cookie,body:{version:0,consent:true,consentVersion:'oyr-registration-v1'}})).status,400);assert.equal((await call('/api/draft',{method:'PATCH',cookie:s.cookie,body:{step:'package',version:0,data:{serviceId:'imaginary',length:18,intendedUse:'PRIVATE',mmsi:'NONE',priority:'STANDARD',delivery:'REGISTERED_MAIL'}}})).status,400);assert.equal((await call('/api/draft',{method:'PATCH',cookie:s.cookie,body:{step:'package',version:0,data:{serviceId:'new-registration',length:-1,intendedUse:'PRIVATE',mmsi:'NONE',priority:'STANDARD',delivery:'REGISTERED_MAIL'}}})).status,400);const r=await call('/api/draft',{method:'PATCH',cookie:s.cookie,body:{step:'package',version:0,data:{serviceId:'new-registration',length:18,intendedUse:'PRIVATE',mmsi:'NONE',priority:'STANDARD',delivery:'REGISTERED_MAIL'}}});assert.equal(r.status,200);assert.equal((await call('/api/draft',{method:'PATCH',cookie:s.cookie,body:{step:'package',version:0,data:{serviceId:'new-registration',length:19,intendedUse:'PRIVATE',mmsi:'NONE',priority:'STANDARD',delivery:'REGISTERED_MAIL'}}})).status,409);
const f=new FormData();f.set('type','Other supporting document');f.set('file',new File([new Uint8Array(10*1024*1024+1)],'large.pdf',{type:'application/pdf'}));assert.equal((await call('/api/draft/documents',{method:'POST',cookie:s.cookie,body:f})).status,400);
});
test('Tracking rate limit applies to unsuccessful attempts',async()=>{let last;for(let i=0;i<22;i++)last=await call('/api/track',{method:'POST',body:{reference:'OYR-INVALID12345',email:'nobody@example.test'},headers:{'cf-connecting-ip':'192.0.2.2'}});assert.equal(last.status,429);});
