import home from '../public/index.html';
import portal from '../public/portal.html';
import {HttpError,object,string,email,validateStep,validateApplication,validateTransition,validateFile,DOCUMENT_TYPES,CONSENT_VERSION,TRANSITIONS,STATES} from './validation.js';
import {db,stmt,catalogue,pricing,hash,id,now,randomToken,reference} from './db.js';
import {safeEmail,submissionEmails,statusEmail} from './email.js';
import {storageConfigured,storagePut,storageExists,storageDelete,storageGet} from './storage.js';
const MAX_BODY=11*1024*1024;
const security={'X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'self' https://chatgpt.com https://*.chatgpt.com",'Permissions-Policy':'camera=(), microphone=(), geolocation=()'};
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{...security,'Content-Type':'application/json','Cache-Control':'private, no-store',...headers}});}
function html(body,status=200){return new Response(body,{status,headers:{...security,'Content-Type':'text/html;charset=utf-8','Cache-Control':'private, no-store'}});}
function sameOrigin(req){const u=new URL(req.url);if(req.headers.get('origin')!==u.origin||req.headers.get('x-oyr-request')!=='1')throw new HttpError(403,'Please use the form on this website.');}
async function readBody(req,max=32000){if(Number(req.headers.get('content-length'))>max)throw new HttpError(413,'The request is too large.');if(!req.body)return new Uint8Array();const reader=req.body.getReader();const chunks=[];let size=0;while(true){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw new HttpError(413,'The request is too large.');}chunks.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}return bytes;}
async function input(req){if(!req.headers.get('content-type')?.startsWith('application/json'))throw new HttpError(415,'Expected JSON form data.');try{return object(JSON.parse(new TextDecoder().decode(await readBody(req))));}catch(e){if(e instanceof HttpError)throw e;throw new HttpError(400,'Please provide valid form data.');}}
async function limit(req,env,scope,max=40){const ip=req.headers.get('cf-connecting-ip')||'unknown';const bucket=Math.floor(Date.now()/600000);const key=await hash(`${scope}:${ip}:${bucket}`);const r=await stmt(env,`INSERT INTO rate_limits(key,count,expires_at) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count`,key,(bucket+1)*600000).first();if(r.count>max)throw new HttpError(429,'Too many attempts. Please wait ten minutes and try again.');}
function cookieToken(req){return (req.headers.get('cookie')||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('oyr_draft='))?.slice(10)||'';}
async function currentDraft(req,env,required=true){const token=cookieToken(req);let row=null;if(/^[a-f0-9]{64}$/.test(token))row=await stmt(env,`SELECT a.* FROM draft_sessions s JOIN applications a ON a.id=s.application_id WHERE s.token_hash=? AND s.expires_at>?`,await hash(token),now()).first();if(!row&&required)throw new HttpError(401,'Your draft session has expired. Please start a new registration.');return row;}
function editable(app){if(app.status!=='DRAFT')throw new HttpError(409,'This application has already been submitted.');}
async function docList(env,appId){return (await stmt(env,'SELECT public_id AS id,type,original_filename AS filename,mime_type AS mimeType,file_size AS size,uploaded_at AS uploadedAt FROM application_documents WHERE application_id=? ORDER BY uploaded_at',appId).all()).results;}
async function draftView(env,app){const payload=JSON.parse(app.draft_payload);let livePrice=null;if(app.status==='DRAFT'&&payload.package){try{livePrice=await pricing(env,payload.package);}catch{livePrice=null;}}return {reference:app.status==='DRAFT'?null:app.reference,status:app.status,version:app.version,payload,documents:await docList(env,app.id),pricing:app.pricing_snapshot?JSON.parse(app.pricing_snapshot):livePrice,submittedAt:app.submitted_at};}
const enc=new TextEncoder();
function adminCookie(req){return (req.headers.get('cookie')||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('oyr_admin='))?.slice(10)||'';}
function b64url(bytes){return btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function unb64url(value){try{const s=value.replace(/-/g,'+').replace(/_/g,'/');const raw=atob(s+'='.repeat((4-s.length%4)%4));return Uint8Array.from(raw,c=>c.charCodeAt(0));}catch{return null;}}
async function hmac(secret,value){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',key,enc.encode(value)));}
function safeEqual(a,b){if(!a||!b||a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a[i]^b[i];return diff===0;}
async function adminSession(env,email){if(!env.ADMIN_SESSION_SECRET||env.ADMIN_SESSION_SECRET.length<32)throw new HttpError(503,'Administrator sign-in is not configured.');const payload=b64url(enc.encode(JSON.stringify({email,exp:Date.now()+12*60*60*1000})));return `${payload}.${b64url(await hmac(env.ADMIN_SESSION_SECRET,payload))}`;}
async function admin(req,env){const token=adminCookie(req),[payload,sig]=token.split('.');if(!payload||!sig||!env.ADMIN_SESSION_SECRET)throw new HttpError(401,'Sign in to access the administration area.');const actual=unb64url(sig),expected=await hmac(env.ADMIN_SESSION_SECRET,payload);if(!safeEqual(actual,expected))throw new HttpError(401,'Your administrator session is invalid. Please sign in again.');let data;try{data=JSON.parse(new TextDecoder().decode(unb64url(payload)));}catch{throw new HttpError(401,'Your administrator session is invalid. Please sign in again.');}const mail=String(data.email||'').trim().toLowerCase();if(!mail||!Number.isFinite(data.exp)||data.exp<Date.now())throw new HttpError(401,'Your administrator session has expired. Please sign in again.');const allowed=(env.ADMIN_EMAILS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);if(!allowed.includes(mail))throw new HttpError(403,'Your account does not have administrator access.');const identity=`local:${mail}`;await stmt(env,`INSERT INTO users(id,identity_id,email,role,created_at) VALUES(?,?,?,'ADMIN',?) ON CONFLICT(identity_id) DO UPDATE SET email=excluded.email`,id(),identity,mail,now()).run();const user=await stmt(env,'SELECT id,email,role FROM users WHERE identity_id=?',identity).first();if(user.role!=='ADMIN')throw new HttpError(403,'Your account does not have administrator access.');return user;}
async function fullApplication(env,ref){return stmt(env,`SELECT a.*,s.name AS service_name,c.name AS customer_name,c.email,c.phone,c.address,c.city,c.postal_code,c.country,c.type AS applicant_type,v.name AS vessel_name,v.type AS vessel_type,v.builder,v.model,v.build_year,v.identification,v.length,v.current_flag,v.intended_use FROM applications a JOIN customers c ON c.id=a.customer_id JOIN vessels v ON v.id=a.vessel_id JOIN services s ON s.id=a.service_id WHERE a.reference=? AND a.status!='DRAFT'`,ref).first();}
async function historyList(env,appId,adminView=false){return (await stmt(env,adminView?`SELECT h.from_status AS fromStatus,h.to_status AS status,h.public_message AS message,h.created_at AS at,h.version,u.email AS changedBy FROM application_status_history h LEFT JOIN users u ON u.id=h.actor_id WHERE h.application_id=? ORDER BY h.version`:`SELECT to_status AS status,public_message AS message,created_at AS at FROM application_status_history WHERE application_id=? ORDER BY version`,appId).all()).results;}
export default {async fetch(req,env,ctx){try{const url=new URL(req.url),path=url.pathname;
if(path.startsWith('/api/')){if(!['GET','POST','PATCH','DELETE'].includes(req.method))throw new HttpError(405,'Method not allowed.');if(req.method!=='GET')sameOrigin(req);db(env);
if(path==='/api/services'&&req.method==='GET')return json({services:await catalogue(env),documentTypes:DOCUMENT_TYPES,consentVersion:CONSENT_VERSION});
if(path==='/api/public-config'&&req.method==='GET')return json({contactEmail:env.PUBLIC_CONTACT_EMAIL||'',whatsapp:env.PUBLIC_WHATSAPP||'',businessAddress:env.PUBLIC_BUSINESS_ADDRESS||''});
if(path==='/api/admin/login'&&req.method==='POST'){await limit(req,env,'admin-login',8);if(!env.ADMIN_PASSWORD||env.ADMIN_PASSWORD.length<16||!env.ADMIN_SESSION_SECRET||env.ADMIN_SESSION_SECRET.length<32)throw new HttpError(503,'Administrator sign-in is not configured.');const body=await input(req),mail=email(body.email).toLowerCase(),password=string(body.password,'Password',256);const allowed=(env.ADMIN_EMAILS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);const supplied=enc.encode(password),expected=enc.encode(env.ADMIN_PASSWORD);if(!allowed.includes(mail)||!safeEqual(supplied,expected))throw new HttpError(401,'Invalid administrator credentials.');const token=await adminSession(env,mail);return json({email:mail},200,{'Set-Cookie':`oyr_admin=${token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=43200${url.protocol==='https:'?'; Secure':''}`});}
if(path==='/api/admin/logout'&&req.method==='POST')return json({ok:true},200,{'Set-Cookie':`oyr_admin=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0${url.protocol==='https:'?'; Secure':''}`});
if(path==='/api/draft'&&req.method==='POST'){await limit(req,env,'draft',15);const existing=await currentDraft(req,env,false);const intake=req.headers.get('content-type')?.startsWith('application/json')?await input(req):{};if(existing&&existing.status==='DRAFT'){if(!intake.enquiry)return json({...await draftView(env,existing),resumedExisting:true});const e=object(intake.enquiry);const serviceId=string(e.serviceId,'Service',60);const packageData={serviceId,length:Number(e.length),intendedUse:'PRIVATE',mmsi:'NONE',priority:'STANDARD',delivery:'REGISTERED_MAIL'};validateStep('package',packageData);await pricing(env,packageData);const payload={...JSON.parse(existing.draft_payload),package:packageData,applicant:{...(JSON.parse(existing.draft_payload).applicant||{}),name:string(e.name,'Full/legal name'),email:email(e.email)},enquiry:{message:string(e.message,'Your plans',2000,false)}};const saved=await stmt(env,`UPDATE applications SET draft_payload=?,updated_at=?,version=version+1 WHERE id=? AND status='DRAFT' RETURNING *`,JSON.stringify(payload),now(),existing.id).first();return json({...await draftView(env,saved),resumedExisting:true});}let initial={};if(intake.enquiry){const e=object(intake.enquiry);const serviceId=string(e.serviceId,'Service',60);await pricing(env,serviceId);initial={package:{serviceId,length:Number(e.length)},applicant:{name:string(e.name,'Full/legal name'),email:email(e.email)},enquiry:{message:string(e.message,'Your plans',2000,false)}};initial.package={...initial.package,intendedUse:'PRIVATE',mmsi:'NONE',priority:'STANDARD',delivery:'REGISTERED_MAIL'};validateStep('package',initial.package);}const token=randomToken(),appId=id(),time=now();await db(env).batch([stmt(env,`INSERT INTO applications(id,reference,status,draft_payload,created_at,updated_at) VALUES(?,?,'DRAFT',?,?,?)`,appId,reference(),JSON.stringify(initial),time,time),stmt(env,'INSERT INTO draft_sessions(token_hash,application_id,expires_at) VALUES(?,?,?)',await hash(token),appId,new Date(Date.now()+7*86400000).toISOString())]);const app=await currentById(env,appId);return json(await draftView(env,app),201,{'Set-Cookie':`oyr_draft=${token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=604800${url.protocol==='https:'?'; Secure':''}`});}
if(path==='/api/draft'&&req.method==='GET')return json(await draftView(env,await currentDraft(req,env)));
if(path==='/api/draft'&&req.method==='PATCH'){const app=await currentDraft(req,env);editable(app);const body=await input(req),step=string(body.step,'Step',20);const part=validateStep(step,body.data);if(step==='package')await pricing(env,part);const payload={...JSON.parse(app.draft_payload),[step]:part};const saved=await stmt(env,`UPDATE applications SET draft_payload=?,updated_at=?,version=version+1 WHERE id=? AND status='DRAFT' AND version=? RETURNING *`,JSON.stringify(payload),now(),app.id,body.version).first();if(!saved)throw new HttpError(409,'Your draft changed in another tab. Refresh before continuing.');return json(await draftView(env,saved));}
if(path==='/api/draft/documents'&&req.method==='POST'){await limit(req,env,'upload',30);const app=await currentDraft(req,env);editable(app);if(!storageConfigured(env))throw new HttpError(503,'Document storage is temporarily unavailable. Please try again.');const count=await stmt(env,'SELECT count(*) AS n FROM application_documents WHERE application_id=?',app.id).first();if(count.n>=10)throw new HttpError(400,'You can upload up to ten documents.');const bytes=await readBody(req,MAX_BODY);let form;try{form=await new Response(bytes,{headers:{'Content-Type':req.headers.get('content-type')||''}}).formData();}catch{throw new HttpError(400,'Choose a document to upload.');}const type=string(form.get('type'),'Document type',80);if(!DOCUMENT_TYPES.includes(type))throw new HttpError(400,'Choose a supported document type.');const file=form.get('file');if(!file||typeof file.arrayBuffer!=='function')throw new HttpError(400,'Choose a document to upload.');const data=new Uint8Array(await file.arrayBuffer());const filename=validateFile(file,data);const docId=id(),publicId=id(),key=`applications/${app.id}/${docId}`,time=now();await storagePut(env,key,data,file.type);try{const result=await db(env).batch([stmt(env,`INSERT INTO application_documents(id,application_id,public_id,type,original_filename,storage_key,mime_type,file_size,sha256,uploaded_at) SELECT ?,?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM applications WHERE id=? AND status='DRAFT') AND (SELECT count(*) FROM application_documents WHERE application_id=?)<10`,docId,app.id,publicId,type,filename,key,file.type,data.length,await hash(data),time,app.id,app.id),stmt(env,`UPDATE applications SET version=version+1,updated_at=? WHERE id=? AND status='DRAFT' AND EXISTS(SELECT 1 FROM application_documents WHERE id=?)`,time,app.id,docId)]);if(!result[0].meta.changes){await storageDelete(env,key);throw new HttpError(409,'The document could not be added. Refresh your application.');}}catch(e){const stored=await stmt(env,'SELECT id FROM application_documents WHERE id=?',docId).first().catch(()=>({id:docId}));if(!stored)await storageDelete(env,key).catch(()=>{});throw e;}return json(await draftView(env,await currentById(env,app.id)),201);}
const draftDoc=path.match(/^\/api\/draft\/documents\/([a-f0-9-]{36})$/);
if(draftDoc&&req.method==='DELETE'){const app=await currentDraft(req,env);editable(app);const doc=await stmt(env,'SELECT storage_key FROM application_documents WHERE public_id=? AND application_id=?',draftDoc[1],app.id).first();if(!doc)throw new HttpError(404,'Document not found.');const r=await db(env).batch([stmt(env,`DELETE FROM application_documents WHERE public_id=? AND application_id=? AND EXISTS(SELECT 1 FROM applications WHERE id=? AND status='DRAFT')`,draftDoc[1],app.id,app.id),stmt(env,`UPDATE applications SET version=version+1,updated_at=? WHERE id=? AND status='DRAFT'`,now(),app.id)]);if(!r[0].meta.changes)throw new HttpError(409,'This application has already been submitted.');await storageDelete(env,doc.storage_key);return json(await draftView(env,await currentById(env,app.id)));}
if(path==='/api/pricing'&&req.method==='POST'){await limit(req,env,'pricing',60);const body=await input(req);return json(await pricing(env,body));}
if(path==='/api/draft/review'&&req.method==='GET'){const app=await currentDraft(req,env);const p=validateApplication(JSON.parse(app.draft_payload));return json({...await draftView(env,app),pricing:await pricing(env,p.package)});}
if(path==='/api/draft/submit'&&req.method==='POST'){await limit(req,env,'submit',15);const app=await currentDraft(req,env);if(app.status!=='DRAFT')return json(await draftView(env,app));const body=await input(req);if(body.consent!==true||body.consentVersion!==CONSENT_VERSION)throw new HttpError(400,'Please confirm the application details before submitting.');if(body.version!==app.version)throw new HttpError(409,'Your application changed. Review the latest details before submitting.');const payload=validateApplication(JSON.parse(app.draft_payload));const docs=await docList(env,app.id);if(!docs.length)throw new HttpError(400,'Upload at least one supporting document.');for(const d of await stmt(env,'SELECT storage_key FROM application_documents WHERE application_id=?',app.id).all().then(x=>x.results)){if(!await storageExists(env,d.storage_key))throw new HttpError(503,'A document is unavailable. Please try again before submitting.');}const price=await pricing(env,payload.package),c=payload.applicant,v=payload.yacht,p=payload.package,time=now(),customerId=id(),vesselId=id();const guard=`WHERE EXISTS(SELECT 1 FROM applications WHERE id=? AND status='DRAFT' AND version=?)`;
await db(env).batch([stmt(env,`INSERT INTO customers(id,type,name,email,phone,address,city,postal_code,country,created_at) SELECT ?,?,?,?,?,?,?,?,?,? ${guard}`,customerId,c.type,c.name,c.email,c.phone,c.address,c.city,c.postalCode,c.country,time,app.id,app.version),stmt(env,`INSERT INTO vessels(id,name,type,builder,model,build_year,identification,length,current_flag,intended_use) SELECT ?,?,?,?,?,?,?,?,?,? ${guard}`,vesselId,v.name,v.type,v.builder,v.model,v.buildYear,v.identification,p.length,v.currentFlag,p.intendedUse,app.id,app.version),stmt(env,`UPDATE applications SET customer_id=?,vessel_id=?,service_id=?,pricing_snapshot=?,consent_at=?,consent_version=?,submitted_at=?,updated_at=?,status='SUBMITTED',version=version+1,last_public_message='Your application has been received.',last_actor_id=NULL WHERE id=? AND status='DRAFT' AND version=?`,customerId,vesselId,p.serviceId,JSON.stringify(price),time,CONSENT_VERSION,time,time,app.id,app.version)]);const saved=await currentById(env,app.id);if(saved.status==='DRAFT')throw new HttpError(409,'Your application changed. Please review it again.');const submitted=await fullApplication(env,saved.reference);if(submitted){const emails=submissionEmails(env,{reference:submitted.reference,email:submitted.email,name:submitted.customer_name,vessel:submitted.vessel_name,service:submitted.service_name,submittedAt:submitted.submitted_at,status:submitted.status,pricing:JSON.parse(submitted.pricing_snapshot),documents:docs.length});(ctx?.waitUntil?ctx.waitUntil(Promise.all([safeEmail(env,emails.customer),emails.admin?safeEmail(env,emails.admin):Promise.resolve()])):Promise.all([safeEmail(env,emails.customer),emails.admin?safeEmail(env,emails.admin):Promise.resolve()]));}return json(await draftView(env,saved),201);}
if(path==='/api/reviews'&&req.method==='GET'){const rows=await stmt(env,`SELECT name,country,rating,comment,published_at AS publishedAt FROM reviews WHERE status='APPROVED' ORDER BY published_at DESC LIMIT 12`).all();return json({items:rows.results});}
if(path==='/api/reviews'&&req.method==='POST'){await limit(req,env,'review',8);const body=await input(req),name=string(body.name,'Name',80),country=string(body.country,'Country',80,false),comment=string(body.comment,'Review',800),rating=Number(body.rating);if(!Number.isInteger(rating)||rating<1||rating>5)throw new HttpError(400,'Choose a rating from 1 to 5.');await stmt(env,`INSERT INTO reviews(id,name,country,rating,comment,status,created_at) VALUES(?,?,?,?,?,'PENDING',?)`,id(),name,country,rating,comment,now()).run();return json({ok:true,message:'Thank you. Your review was submitted for moderation.'},201);}
if(path==='/api/track'&&req.method==='POST'){await limit(req,env,'tracking',20);const body=await input(req);const ref=string(body.reference,'Reference',40).toUpperCase();const mail=email(body.email);const app=await stmt(env,`SELECT a.id,a.reference,a.status,a.submitted_at,a.updated_at,v.name AS vessel,s.name AS service FROM applications a JOIN customers c ON c.id=a.customer_id JOIN vessels v ON v.id=a.vessel_id JOIN services s ON s.id=a.service_id WHERE a.reference=? AND c.email=? AND a.status!='DRAFT'`,ref,mail).first();if(!app)return json({application:null,message:'No application matched those details. Please check your reference and application email.'});return json({application:{reference:app.reference,vessel:app.vessel,service:app.service,status:app.status,submittedAt:app.submitted_at,updatedAt:app.updated_at,history:await historyList(env,app.id)}});}
if(path.startsWith('/api/admin/')){const user=await admin(req,env);
if(path==='/api/admin/me'&&req.method==='GET')return json({email:user.email});
if(path==='/api/admin/reviews'&&req.method==='GET'){const rows=await stmt(env,`SELECT id,name,country,rating,comment,status,created_at AS createdAt,published_at AS publishedAt FROM reviews ORDER BY created_at DESC LIMIT 100`).all();return json({items:rows.results});}
const reviewAction=path.match(/^\/api\/admin\/reviews\/([a-f0-9-]{36})$/);if(reviewAction&&req.method==='PATCH'){const body=await input(req),status=string(body.status,'Review status',20);if(!['APPROVED','REJECTED'].includes(status))throw new HttpError(400,'Choose a valid review status.');const r=await stmt(env,`UPDATE reviews SET status=?,published_at=? WHERE id=? RETURNING id`,status,status==='APPROVED'?now():null,reviewAction[1]).first();if(!r)throw new HttpError(404,'Review not found.');return json({ok:true});}
if(reviewAction&&req.method==='DELETE'){const r=await stmt(env,'DELETE FROM reviews WHERE id=? RETURNING id',reviewAction[1]).first();if(!r)throw new HttpError(404,'Review not found.');return json({ok:true});}

if(path==='/api/admin/applications'&&req.method==='GET'){const q=(url.searchParams.get('q')||'').trim().slice(0,120),status=url.searchParams.get('status')||'',page=Math.max(1,Math.min(10000,Number(url.searchParams.get('page'))||1));if(status&&!STATES.slice(1).includes(status))throw new HttpError(400,'Unknown status filter.');const where=`a.status!='DRAFT' AND (?='' OR a.status=?) AND (?='' OR instr(lower(a.reference||' '||c.name||' '||v.name),lower(?))>0)`;const rows=await stmt(env,`SELECT a.reference,c.name AS customer,v.name AS vessel,s.name AS service,a.status,a.submitted_at AS submittedAt FROM applications a JOIN customers c ON c.id=a.customer_id JOIN vessels v ON v.id=a.vessel_id JOIN services s ON s.id=a.service_id WHERE ${where} ORDER BY a.submitted_at DESC LIMIT 25 OFFSET ?`,status,status,q,q,(page-1)*25).all();const total=await stmt(env,`SELECT count(*) AS n FROM applications a JOIN customers c ON c.id=a.customer_id JOIN vessels v ON v.id=a.vessel_id WHERE ${where}`,status,status,q,q).first();const stats=await stmt(env,"SELECT status,count(*) AS count FROM applications WHERE status!='DRAFT' GROUP BY status").all();const notifications=await stmt(env,'SELECT count(*) AS n FROM notifications WHERE read_at IS NULL').first();return json({items:rows.results,total:total.n,page,stats:stats.results,unread:notifications.n});}
const detail=path.match(/^\/api\/admin\/applications\/(OYR-[A-Z2-9]{12})$/);if(detail&&req.method==='GET'){const a=await fullApplication(env,detail[1]);if(!a)throw new HttpError(404,'Application not found.');return json({reference:a.reference,status:a.status,version:a.version,customer:{type:a.applicant_type,name:a.customer_name,email:a.email,phone:a.phone,address:a.address,city:a.city,postalCode:a.postal_code,country:a.country},vessel:{name:a.vessel_name,type:a.vessel_type,builder:a.builder,model:a.model,buildYear:a.build_year,identification:a.identification,length:a.length,currentFlag:a.current_flag,intendedUse:a.intended_use},service:a.service_name,pricing:JSON.parse(a.pricing_snapshot),documents:await docList(env,a.id),history:await historyList(env,a.id,true),submittedAt:a.submitted_at,updatedAt:a.updated_at,consentAt:a.consent_at,consentVersion:a.consent_version,enquiry:JSON.parse(a.draft_payload).enquiry?.message||'',allowedTransitions:TRANSITIONS[a.status]||[]});}
const change=path.match(/^\/api\/admin\/applications\/(OYR-[A-Z2-9]{12})\/status$/);if(change&&req.method==='POST'){const a=await fullApplication(env,change[1]);if(!a)throw new HttpError(404,'Application not found.');const body=await input(req);validateTransition(a.status,body.status);const message=string(body.message,'Customer update',600,false);if(body.status==='ADDITIONAL_DOCUMENTS_REQUIRED'&&!message)throw new HttpError(400,'Explain which documents are required and how the customer should provide them.');const changed=await stmt(env,`UPDATE applications SET status=?,updated_at=?,version=version+1,last_actor_id=?,last_public_message=? WHERE id=? AND status=? AND version=? RETURNING reference`,body.status,now(),user.id,message||null,a.id,a.status,body.version).first();if(!changed)throw new HttpError(409,'This application changed. Refresh before updating its status.');const recipient=await stmt(env,`SELECT c.email FROM applications a JOIN customers c ON c.id=a.customer_id WHERE a.reference=?`,changed.reference).first();if(recipient?.email)(ctx?.waitUntil?ctx.waitUntil(safeEmail(env,statusEmail(env,{reference:changed.reference,email:recipient.email,status:body.status},message))):safeEmail(env,statusEmail(env,{reference:changed.reference,email:recipient.email,status:body.status},message)));return json({reference:changed.reference,status:body.status});}
const download=path.match(/^\/api\/admin\/documents\/([a-f0-9-]{36})$/);if(download&&req.method==='GET'){const d=await stmt(env,`SELECT d.* FROM application_documents d JOIN applications a ON a.id=d.application_id WHERE d.public_id=? AND a.status!='DRAFT'`,download[1]).first();if(!d)throw new HttpError(404,'Document not found.');const item=await storageGet(env,d.storage_key);if(!item)throw new HttpError(503,'Document temporarily unavailable.');return new Response(item.body,{headers:{...security,'Content-Type':d.mime_type,'Content-Length':String(d.file_size),'Content-Disposition':`attachment; filename="document"; filename*=UTF-8''${encodeURIComponent(d.original_filename).replaceAll("'",'%27')}`,'Content-Security-Policy':"sandbox; default-src 'none'",'Cache-Control':'private, no-store'}});}
const read=path.match(/^\/api\/admin\/applications\/(OYR-[A-Z2-9]{12})\/read$/);if(read&&req.method==='POST'){await stmt(env,'UPDATE notifications SET read_at=? WHERE application_id=(SELECT id FROM applications WHERE reference=?) AND read_at IS NULL',now(),read[1]).run();return json({ok:true});}
throw new HttpError(404,'Not found.');}
throw new HttpError(404,'Not found.');}
if(!['GET','HEAD'].includes(req.method))throw new HttpError(405,'Method not allowed.');
if(path==='/'||path==='/index.html')return html(home);
if(path==='/register'){
  let app=await currentDraft(req,env,false),setCookie='';
  if(!app){
    const token=randomToken(),appId=id(),time=now();
    await db(env).batch([
      stmt(env,`INSERT INTO applications(id,reference,status,draft_payload,created_at,updated_at) VALUES(?,?,'DRAFT',?,?,?)`,appId,reference(),'{}',time,time),
      stmt(env,'INSERT INTO draft_sessions(token_hash,application_id,expires_at) VALUES(?,?,?)',await hash(token),appId,new Date(Date.now()+7*86400000).toISOString())
    ]);
    app=await currentById(env,appId);
    setCookie=`oyr_draft=${token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=604800${url.protocol==='https:'?'; Secure':''}`;
  }
  const config={services:await catalogue(env),documentTypes:DOCUMENT_TYPES,consentVersion:CONSENT_VERSION,draft:await draftView(env,app)};
  const bootstrap=encodeURIComponent(JSON.stringify(config));
  const shell=portal
    .replace('<main class="wrap portal-wrap" id="portal"><p role="status">Loading your registration workspace…</p></main>',`<main class="wrap portal-wrap" id="portal" data-oyr-bootstrap="${bootstrap}"></main>`)
    .replace('/portal.js"></script>','/portal.js?v=20260926-main-registration"></script>');
  return new Response(shell,{headers:{...security,'Content-Type':'text/html;charset=utf-8','Cache-Control':'private, no-store',...(setCookie?{'Set-Cookie':setCookie}:{})}});
}
if(['/track','/admin','/admin/login'].includes(path)||/^\/admin\/applications\/OYR-[A-Z2-9]{12}$/.test(path))return html(portal);
if(path==='/health')return json({ok:true});
if(env.ASSETS)return env.ASSETS.fetch(req);
return html('<h1>Page not found</h1>',404);
}catch(e){if(!(e instanceof HttpError))console.error('OYR request failed',{path:new URL(req.url).pathname,error:e?.message});return json({error:e instanceof HttpError?e.message:'The service is temporarily unavailable. Your form has not been cleared. Please try again.'},e instanceof HttpError?e.status:503);}}};
async function currentById(env,appId){return stmt(env,'SELECT * FROM applications WHERE id=?',appId).first();}
