// Local-only SIWC simulator. Not imported or bundled into the deployed Worker.
// Identity headers are stripped and can only be created by this loopback proxy.
import http from 'node:http';
import {spawn} from 'node:child_process';
import {randomBytes} from 'node:crypto';
const nonce=randomBytes(32).toString('hex');
const child=spawn(process.execPath,['node_modules/wrangler/bin/wrangler.js','dev','--local','--ip','127.0.0.1','--port','8788','--persist-to','.wrangler/state'],{stdio:'inherit',env:{...process.env,CHOKIDAR_USEPOLLING:'true',WRANGLER_SEND_METRICS:'false',CLOUDFLARE_CF_FETCH_ENABLED:'false',WRANGLER_LOG_PATH:'.wrangler/logs',WRANGLER_REGISTRY_PATH:'.wrangler/registry',MINIFLARE_REGISTRY_PATH:'.wrangler/registry'}});
const server=http.createServer(async(req,res)=>{try{if(!['127.0.0.1:5173','localhost:5173'].includes(req.headers.host)){res.writeHead(403).end();return;}const u=new URL(req.url,'http://'+req.headers.host);if(u.pathname==='/signin-with-chatgpt'||u.pathname==='/signout-with-chatgpt'){if(req.headers['sec-fetch-site']==='cross-site'){res.writeHead(403).end();return;}let target=u.searchParams.get('return_to')||'/admin';if(!target.startsWith('/')||target.startsWith('//'))target='/admin';const login=u.pathname==='/signin-with-chatgpt';res.writeHead(302,{'Location':target,'Set-Cookie':`oyr_local_auth=${login?nonce:''}; Path=/; HttpOnly; SameSite=Strict${login?'':'; Max-Age=0'}`,'Cache-Control':'no-store'}).end();return;}const headers={...req.headers};for(const key of Object.keys(headers)){if(key.startsWith('oai-authenticated-')||key==='cf-connecting-ip')delete headers[key];}const cookies=(headers.cookie||'').split(';').map(x=>x.trim());if(cookies.includes('oyr_local_auth='+nonce)){headers['oai-authenticated-user-id']='local-oyr-admin';headers['oai-authenticated-user-email']='abdulshahin60@gmail.com';}headers.cookie=cookies.filter(x=>!x.startsWith('oyr_local_auth=')).join('; ');headers['cf-connecting-ip']='127.0.0.1';const upstream=http.request({host:'127.0.0.1',port:8788,path:req.url,method:req.method,headers},response=>{res.writeHead(response.statusCode,response.headers);response.pipe(res);});upstream.on('error',()=>{res.writeHead(503,{'Content-Type':'text/plain'}).end('Local preview starting. Please retry shortly.');});req.pipe(upstream);}catch{res.writeHead(500).end('Local preview error.');}});
server.listen(5173,'127.0.0.1',()=>console.log('Ocean preview: http://localhost:5173\nLocal admin sign-in is simulated for testing only.'));
const close=()=>{child.kill();server.close();};process.on('SIGINT',close);process.on('SIGTERM',close);child.on('exit',()=>server.close());
